//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongMachTu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBaoCaoThuoc
    {
        public string MaBaoCao { get; set; }
        public string MaThuoc { get; set; }
        public int SoLuong { get; set; }
        public int SoLanDung { get; set; }
    
        public virtual BaoCaoThuoc BaoCaoThuoc { get; set; }
        public virtual Thuoc Thuoc { get; set; }
    }
}
