//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongMachTu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBaoCaoDoanhThu
    {
        public string MaBaoCao { get; set; }
        public System.DateTime Ngay { get; set; }
        public double TiLe { get; set; }
    
        public virtual BaoCaoDoanhThuThang BaoCaoDoanhThuThang { get; set; }
        public virtual DoanhThuNgay DoanhThuNgay { get; set; }
    }
}
