//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongMachTu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDanhSachKham
    {
        public System.DateTime NgayKham { get; set; }
        public string BenhNhan { get; set; }
        public int ThuTu { get; set; }
    
        public virtual BenhNhan BenhNhan1 { get; set; }
    }
}
