//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongMachTu.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DesignEntities : DbContext
    {
        public DesignEntities()
            : base("name=DesignEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BacSi> BacSis { get; set; }
        public virtual DbSet<BaoCaoDoanhThuThang> BaoCaoDoanhThuThangs { get; set; }
        public virtual DbSet<BaoCaoThuoc> BaoCaoThuocs { get; set; }
        public virtual DbSet<BenhNhan> BenhNhans { get; set; }
        public virtual DbSet<ChiTietBaoCaoDoanhThu> ChiTietBaoCaoDoanhThus { get; set; }
        public virtual DbSet<ChiTietBaoCaoThuoc> ChiTietBaoCaoThuocs { get; set; }
        public virtual DbSet<ChiTietDanhSachKham> ChiTietDanhSachKhams { get; set; }
        public virtual DbSet<ChiTietDonThuoc> ChiTietDonThuocs { get; set; }
        public virtual DbSet<DoanhThuNgay> DoanhThuNgays { get; set; }
        public virtual DbSet<DonThuoc> DonThuocs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<LoaiBenh> LoaiBenhs { get; set; }
        public virtual DbSet<PhieuKham> PhieuKhams { get; set; }
        public virtual DbSet<Thuoc> Thuocs { get; set; }
        public virtual DbSet<TrieuChung> TrieuChungs { get; set; }
    }
}
