//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongMachTu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaSo { get; set; }
        public System.DateTime NgayLap { get; set; }
        public int TienKham { get; set; }
        public int TienThuoc { get; set; }
        public int TongTien { get; set; }
        public string KhachHang { get; set; }
    
        public virtual BenhNhan BenhNhan { get; set; }
    }
}
