//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongMachTu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuKham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuKham()
        {
            this.DonThuocs = new HashSet<DonThuoc>();
            this.LoaiBenhs = new HashSet<LoaiBenh>();
            this.TrieuChungs = new HashSet<TrieuChung>();
        }
    
        public string MaSo { get; set; }
        public System.DateTime NgayKham { get; set; }
        public string HoaDon { get; set; }
        public string BacSi { get; set; }
        public string BenhNhan { get; set; }
    
        public virtual BacSi BacSi1 { get; set; }
        public virtual BenhNhan BenhNhan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonThuoc> DonThuocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoaiBenh> LoaiBenhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrieuChung> TrieuChungs { get; set; }
    }
}
